name: DangerousCaves
version: '${version}'
config-version: 24
main: me.imdanix.caves.DangerousCaves
api-version: '1.21'
authors: [imDaniX, Evil-Lootlye]
description: '${description}'
softdepend: [PlaceholderAPI]
commands:
  dangerouscaves:
    aliases: [dcaves]
    usage: '/<command> [summon|kill|tick|reload]'
    permission: dangerouscaves.command